#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

server:
  port: 8080

spring:
  #settings of postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/bankcards
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
