#
# application.yml — главный конфигурационный файл Spring Boot.

# Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

server:
  port: 8080

spring:
  #settings of postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/bankcards
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  #settings of liquibase
  liquibase:
    change-log: classpath:/db/migration/db.changelog-master.yaml
    enabled: true
    liquibase-schema: bankcards
  #settings of hibernate
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG

#Security
security:
  jwt:
    secret_key: 4eeab38d706831be4b36612ead768ef8182d1dd6f0e14e5dc934652e297fb16a
    access_token_expiration: 36000000 # 10 hours
    refresh_token_expiration: 252000000 # 7 days

# Swagger configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    url: /api-docs
    disable-swagger-default-url: true
    config-url: /api-docs/swagger-config
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none
    display-operation-id: true
    display-request-duration: true
    persist-authorization: true
    oauth:
      client-id: swagger-ui
      client-secret: secret
      use-pkce-with-authorization-code-grant: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  model-and-view-allowed: true
  override-with-generic-response: false